version: '3'
services:

  lb_ef:
    image: nginx:latest
    ports:
      - 8082:80
    volumes:
      - ./lb/default.conf:/etc/nginx/conf.d/default.conf
    command: /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
    restart: always
    networks:
      - front

  web_ef:
    image: aspnetcore_mssql_ef
    build:
      context: ./src
      dockerfile: ./WebApplicationEF/Dockerfile
    ports:
      - 80
    environment:
      ConnectionStrings__BloggingDatabase: "Data Source=mssql_ef;Database=test;User ID=sa;Password=iamSuperUser!!!!12345;Connect Timeout=60;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - front
      - db

  mssql_ef:
    container_name: mssql_ef
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports:
      - 1434:1433
    volumes:
      - ./sql:/usr/src/app
      - ./src/DatabaseEF/dbo/Tables/:/usr/src/app/table/
    working_dir: /usr/src/app
    command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: iamSuperUser!!!!12345
      MSSQL_PID: Standard
      # japanese should use 1041, otherwise garbage character
      MSSQL_LCID: 1041
      MSSQL_COLLATION: Japanese_Bushu_Kakusu_140_CI_AS
      SQLCMDUSER: SA
      SQLCMDSERVER: localhost,1433
      SQLCMDDBNAME: test
    restart: always
    networks:
      - db

networks:
  front:
    driver: bridge
  db:
    driver: bridge
