apiVersion: v1
kind: Service
metadata:
  name: webserver-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-1:123456789012:certificate/abcd1234-abcd-abcd-abcd-12345678abcd
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
spec:
  externalTrafficPolicy: Local
