version: '3'
services:

  console:
    image: console:dev
    build:
      context: ./DockerComposeDnsResolution
    depends_on:
        - api
    environment:
      HOSTADDRESS: api
      URL: http://api
    networks:
      - api

  api:
    image: api:dev
    build:
      context: ./WebApp
    ports:
      - 5555:80
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - api

networks:
  api:
    driver: bridge
