version: '3'
services:

  lb_ef:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./lb/default.conf:/etc/nginx/conf.d/default.conf
    command: /usr/sbin/nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
    restart: always
    networks:
      - front

  web_ef:
    image: aspnetcore_ef
    build:
      context: ./src
      dockerfile: ./WebApplicationEF/Dockerfile
    ports:
      - 80
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - front
      - db

  mysql_ef:
    container_name: mysql_ef
    image: mysql:5.7.12
    command: --character-set-server=utf8mb4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    restart: always
    networks:
      - db

networks:
  front:
    driver: bridge
  db:
    driver: bridge
