apiVersion: v1
kind: Service
metadata:
  name: webserver-svc
spec:
  selector:
    app: webserver
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
