version: '3'
services:

  mysql_test:
    image: mysql:5.7.12
    command: --character-set-server=utf8mb4
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./entityframework_mysql/sql/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always

