name: aws/OpenIdConnectorProvider
on: push

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    defaults:
      run:
        working-directory: ./aws/OpenIdConnectorProvider/ServerCertificateChain
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet run --project ./ServerCertificateChain.csproj
      - run: echo | openssl s_client -servername oidc.eks.ap-northeast-1.amazonaws.com -showcerts -connect oidc.eks.ap-northeast-1.amazonaws.com:443 2>&- | tac | sed -n '/-----END CERTIFICATE-----/,/-----BEGIN CERTIFICATE-----/p; /-----BEGIN CERTIFICATE-----/q' | tac | openssl x509 -text -noout
      - run: echo | openssl s_client -servername oidc.eks.ap-northeast-1.amazonaws.com -showcerts -connect oidc.eks.ap-northeast-1.amazonaws.com:443 2>&- | tac | sed -n '/-----END CERTIFICATE-----/,/-----BEGIN CERTIFICATE-----/p; /-----BEGIN CERTIFICATE-----/q' | tac | openssl x509 -fingerprint -sha1 -noout | sed 's/://g' | awk -F= '{print tolower($2)}'
